### ISSUE TITLE
Заберите репозиторий.

### ISSUE THREAD

**Issue by ChALkeR** [Polandr/lindblad_eq#7]
Я инициировал передачу репозитория @Polandr.
Могу вместо этого передать @Kristofer76, если надо. Но лучше сами разберитесь.
Если хотите удалять — удаляйте, но для этого сначала заберите себе.

/cc @Polandr, @Kristofer76

**Comment by Polandr** [comment]
Взял себе, оставлю на память ;)

**Comment by ChALkeR** [comment]
Ага, спасибо.
